services:
  journal:
    build: .
    ports:
      - "10650-10699:5000"
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./app:/app/app

volumes:
  mysql_data:
