services:
  python_app:
    build: .
    container_name: python_app
    ports:
      - "5000:5000"
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./app/app

volumes:
  mysql_data: