services:
  youtube:
    build: .
    ports:
      - "5000:5000"
    networks:
      xss-net:
        ipv4_address: 172.20.234.2

  bot:
    build: ./bot
    depends_on:
      - youtube
    networks:
      - xss-net

networks:
  xss-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.234.0/24
